/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2aeafdf5-5e8b-4969-afb8-6bd2abb30b58",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zhH7nEsEG",
    "aws_user_pools_web_client_id": "m6edr1vuqo2mkibqhs2q6gpn4",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://nl3d4qvjsrf3llieqtqxqvrhha.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sd4ibiuiene4za2nr5wbtae3yq",
    "aws_user_files_s3_bucket": "finalyearprochatapp2cd43c5360b1416c9a0884a61bc664652-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
